In [3]:
import tensorflow as tf
import numpy as np
import matplotlib as plt
%matplotlib inline

In [4]:
Hello = tf.constant("Herro")

In [5]:
World = tf.constant("World")

In [6]:
with tf.Session() as sess:
    result = sess.run(Hello + World)

In [7]:
result

b'HerroWorld'

In [8]:
a = tf.constant(1)

In [9]:
b = tf.constant(2
            )

In [10]:
a + b


<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [13]:
result

3

In [14]:
#random normal distribution
distRand = tf.random_normal((4,4), mean = 0, stddev = 1000)

In [15]:
#random uniform distribution
distUni = tf.random_uniform((4,4), minval=-100, maxval=100)

In [16]:
#Graphs
node1 = tf.constant(10)
node2 = tf.constant(10)
node3 = node1 + node2

In [17]:
with tf.Session() as sess:
    result = sess.run(node3)

In [18]:
result

20

In [19]:
#Placeholders and Variables-

In [20]:
tensor = tf.random_normal((4,4), 0, 1)

In [21]:
variable = tf.Variable(initial_value=tensor)

In [22]:
sess = tf.InteractiveSession()

In [23]:
init = tf.global_variables_initializer()
sess.run(init)
sess.run(variable
        )

array([[-1.37978852, -0.01298273, -1.0050025 ,  0.44231841],
       [-0.96723223,  0.15759081, -0.26473904,  0.28838894],
       [-0.18050089,  0.3019225 ,  1.9883852 ,  0.45484963],
       [-0.18755552,  0.05766303,  0.04185689, -0.17793326]], dtype=float32)

In [24]:
#simple quick classification NN

In [25]:
np.random.seed(101)

In [26]:
tf.set_random_seed(101)

In [27]:
#Gurt out some random data points
random_points = np.random.uniform(0, 100, (5,5))

In [28]:
random_points_2 = np.random.uniform(0, 100, (5,1))

In [29]:
random_points

array([[ 51.63986277,  57.06675869,   2.84742265,  17.15216562,
         68.52769817],
       [ 83.38968626,  30.69662197,  89.36130797,  72.15438618,
         18.99389542],
       [ 55.42275911,  35.2131954 ,  18.18924027,  78.56017619,
         96.54832224],
       [ 23.23536618,   8.35614337,  60.35484223,  72.89927573,
         27.62388285],
       [ 68.53063288,  51.78674742,   4.84845374,  13.78692376,
         18.69674261]])

In [30]:
random_points_2


array([[ 99.43179012],
       [ 52.06653967],
       [ 57.87895355],
       [ 73.48190583],
       [ 54.19617722]])

In [31]:
a = tf.placeholder(tf.float32)

In [32]:
b = tf.placeholder(tf.float32
                  )

In [33]:
add = a + b

In [34]:
mult_cult = tf.matmul(a, b)

In [35]:
with tf.Session() as sess:
    result = sess.run(add, feed_dict={a: random_points, b: random_points_2})
    print(result)

[[ 151.07165527  156.49855042  102.27921295  116.58396149  167.95948792]
 [ 135.45622253   82.76316071  141.42784119  124.22093201   71.06043243]
 [ 113.30171204   93.09214783   76.06819153  136.43911743  154.42727661]
 [  96.7172699    81.83804321  133.83674622  146.38117981  101.10578918]
 [ 122.72680664  105.98292542   59.04463196   67.98310089   72.89292145]]


In [36]:
n1_features = 10
#3 layers of dense neurons
n1_neurons = 3

In [38]:
x = tf.placeholder(tf.float32, (None, n1_features))

In [39]:
W = tf.Variable(tf.random_normal([n1_features, n1_neurons]))

In [40]:
b = tf.Variable(tf.ones(n1_neurons))

In [41]:
xW = tf.matmul(x, W)

In [45]:
z = tf.add(xW , b)

In [47]:
#activation function yeet
a = tf.sigmoid(z)