In [26]:
import tensorflow as tf
import numpy as np
import matplotlib as plt
%matplotlib inline

In [3]:
Hello = tf.constant("Herro")

In [4]:
World = tf.constant("World")

In [6]:
with tf.Session() as sess:
    result = sess.run(Hello + World)

In [8]:
result

b'HerroWorld'

In [9]:
a = tf.constant(1)

In [10]:
b = tf.constant(2
            )

In [12]:
a + b


<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [16]:
result

3

In [18]:
#random normal distribution
distRand = tf.random_normal((4,4), mean = 0, stddev = 1000)

In [20]:
#random uniform distribution
distUni = tf.random_uniform((4,4), minval=-100, maxval=100)

In [23]:
#Graphs
node1 = tf.constant(10)
node2 = tf.constant(10)
node3 = node1 + node2

In [24]:
with tf.Session() as sess:
    result = sess.run(node3)

In [25]:
result

20

In [27]:
#Placeholders and Variables-

In [28]:
tensor = tf.random_normal((4,4), 0, 1)

In [29]:
variable = tf.Variable(initial_value=tensor)

In [30]:
sess = tf.InteractiveSession()

In [34]:
init = tf.global_variables_initializer()
sess.run(init)
sess.run(variable
        )

array([[ 0.96117663, -1.14659214, -0.36878812,  0.22816849],
       [ 0.01736601, -1.22327638, -0.46199042,  2.38109064],
       [ 0.86339265, -1.46944857,  1.0987221 ,  0.43852717],
       [ 0.91979027,  0.21080096,  1.76027513, -1.58879232]], dtype=float32)

In [35]:
#simple quick classification NN

In [36]:
np.random.seed(101)

In [37]:
tf.set_random_seed(101)

In [38]:
#Gurt out some random data points
random_points = np.random.uniform(0, 100, (5,5))

In [40]:
random_points_2 = np.random.uniform(0, 100, (5,1))

In [41]:
random_points

array([[ 51.63986277,  57.06675869,   2.84742265,  17.15216562,
         68.52769817],
       [ 83.38968626,  30.69662197,  89.36130797,  72.15438618,
         18.99389542],
       [ 55.42275911,  35.2131954 ,  18.18924027,  78.56017619,
         96.54832224],
       [ 23.23536618,   8.35614337,  60.35484223,  72.89927573,
         27.62388285],
       [ 68.53063288,  51.78674742,   4.84845374,  13.78692376,
         18.69674261]])

In [42]:
random_points_2


array([[ 99.43179012],
       [ 52.06653967],
       [ 57.87895355],
       [ 73.48190583],
       [ 54.19617722]])

In [44]:
a = tf.placeholder(tf.float32)

In [45]:
b = tf.placeholder(tf.float32
                  )

In [46]:
add = a + b

In [48]:
mult_cult = tf.matmul(a, b)

In [50]:
with tf.Session() as sess:
    result = sess.run(add, feed_dict={a: random_points, b: random_points_2})
    print(result)

[[ 151.07165527  156.49855042  102.27921295  116.58396149  167.95948792]
 [ 135.45622253   82.76316071  141.42784119  124.22093201   71.06043243]
 [ 113.30171204   93.09214783   76.06819153  136.43911743  154.42727661]
 [  96.7172699    81.83804321  133.83674622  146.38117981  101.10578918]
 [ 122.72680664  105.98292542   59.04463196   67.98310089   72.89292145]]
